######################################################################
# Automatically generated by qmake (2.01a) ?? ???. 2 13:28:06 2013
######################################################################

TEMPLATE = app
TARGET = start
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainwidget.h
SOURCES += main.cpp mainwidget.cpp
FORMS += mainwidget.ui

