######################################################################
# Automatically generated by qmake (2.01a) ?? ??? 11 17:02:16 2014
######################################################################

TEMPLATE = app
TARGET = lib_target
DEPENDPATH += .

INCLUDEPATH += . \
	    $$PWD \
	    $$PWD/math \
	    $$PWD/static


include($$PWD/subdirs.pri)
include($$PWD/lib.pri)



# Input
SOURCES += main.cpp


