######################################################################
# Automatically generated by qmake (2.01a) ?? ??? 24 16:26:05 2012
######################################################################

TEMPLATE = app
TARGET = start_ipoteka
DEPENDPATH += .
INCLUDEPATH += .

QT += widgets

# Input
HEADERS += icalc.h mainwidget.h
FORMS += mainwidget.ui
SOURCES += icalc.cpp main.cpp mainwidget.cpp

